rabot-utils

diff --git a/anthos-release b/anthos-release
--- a/anthos-release
+++ b/anthos-release
@@ -1,19 +1,22 @@
 #!/bin/bash
 
-. rabot-common
+. rabot-utils
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot-common" >&2
+  echo "$0: Error while sourcing rabot-utils" >&2
   exit 1
 fi
 
-checkForHelp $1
-minNumArgs 2 $#
-
-: << DOCSTRING
+function showHelp
+{
+cat << DOCSTRING
 Usage: $(basename "$0") BUILDDIR RELEASEDIR
 
 '$(basename "$0")' builds a release directory of an anthos project.
 DOCSTRING
+}
+
+checkForHelp $1
+minNumArgs 2 $#
 
 buildDir="$1"
 releaseDir="$2"
diff --git a/anthos-tidy-html b/anthos-tidy-html
--- a/anthos-tidy-html
+++ b/anthos-tidy-html
@@ -1,19 +1,22 @@
 #!/bin/bash
 
-. rabot-common
+. rabot-utils
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot-common" >&2
+  echo "$0: Error while sourcing rabot-utils" >&2
   exit 1
 fi
 
-checkForHelp $1
-minNumArgs 1 $#
-
-: << DOCSTRING
+function showHelp
+{
+cat << DOCSTRING
 Usage: $(basename "$0") WORKINGDIR
 
 '$(basename "$0")' tidies up the HTML files in the directory tree 'WORKINGDIR'
 DOCSTRING
+}
+
+checkForHelp $1
+minNumArgs 1 $#
 
 
 function tidyfile
